# poke again again

task:
  name: Hack
  compute_engine_instance:
    image_project: pg-vm-images-aio
    image: family/pg-aio-freebsd-13-0
    platform: freebsd
    cpu: 4
    memory: 8G
    disk: 50
  hello_script:
    - sudo dmesg
    - sudo gpart show da0
    - sudo camcontrol reprobe da0
    - sudo gpart recover da0
    - sudo camcontrol reprobe da0
    - sudo gpart commit da0 || true
    - sudo gpart show da0
    - sudo swapoff -a || true
    - sudo gpart delete -i 3 da0
    - sudo gpart add -t freebsd-ufs -l data8k -s 10G -a 8192 da0 || true
