# poke again again

task:
  name: Hack
  compute_engine_instance:
    image_project: pg-vm-images-aio
    image: family/pg-aio-freebsd-13-0
    platform: freebsd
    cpu: 4
    memory: 8G
    disk: 50
  hello_script:
    - sudo dmesg
    - echo "==loader=="
    - cat /boot/loader.conf || true
    - echo "==rc=="
    - cat /etc/rc.conf || true
    - echo "==sysctl=="
    - sysctl -a | grep timecounter
    - echo "==sysctl2=="
    - sysctl -a | grep -i tsc

